#	Makefile generated by imake - do not edit!
#	$XConsortium: imake.c,v 1.51 89/12/12 12:37:30 jim Exp $
#
#	The cpp used on this machine replaces all newlines and multiple tabs and
#	spaces in a macro expansion with a single space. Imake tries to compensate
#	for this, but is not always successful.
#

#
#	This template is not automatically generated by imake, and can
#	be found in PLS UNXDEV as IMKDATAS. This file was generated from
#	the UAE IMKOPC template produced by 7B21.
#

		DEPEND = makedepend
		IMAKE = imake

#	34

#	41

#	48

#	62

#	67

		SHELL = /bin/ksh
		TOP = $(TOPDIR)
		AS = as
		CC = cc
		CPP = /lib/cpp
		CP = cp -f
		LD = ld
		LINT = lint
		INSTALL = /lbtools/bin/bsdinstall
		TAGS = ctags
		RM = rm -f
		MV = mv
		LN = ln -s
		AR = ar rcul
		RANLIB = ranlib
		LS = ls
		LINTOPTS	= -ax
		LINTLIBFLAG	= -o
		MAKE	= make
		STD_DEFINES	= -DSYSV
		CDEBUGFLAGS = -O

#	75

		DEFINES =

#	84

		PATHSEP		= /
		CFLAGS		= $(CDEBUGFLAGS) $(INCLUDES) $(STD_DEFINES) $(DEFINES)
		LINTFLAGS	= $(LINTOPTS) $(INCLUDES) $(STD_DEFINES) $(DEFINES) -DLINT

		LDFLAGS 	= -s $(CDEBUGFLAGS) $(LIBSEARCHDIRS)

#	94

		INSTUIDFLAGS	= -m 4755
		INSTLIBFLAGS	= -m 0664
		INSTINCFLAGS	= -m 0444
		INSTMANFLAGS	= -m 0444
		INSTAPPFLAGS	- -m 0444
		INSTALLFLAGS	= -m 0775

		INSTALL = /itdserv/bin/bsdinstall

		INCLUDES	= $(IPATH)
		MACROFILE	= imkhpux.macros
		IMAKE_CMD	= $(IMAKE) -s Makefile
		RM_CMD		= if [ -d ptrepository ]; then rm -r ptrepository; fi; \
					  $(RM) *.CKP *.ln *.BAK *.bak *.o core errs ,*	*~ *.a \
					  tags TAGS make.log *.uidt *.uili
		UIDT		= uidt
		UIDLFLAGS	= 

.uidl.uidt:	
				$(UIDT) $(UIDLFLAGS) -o $*.uidt $<

.uidl.uili:
				$(UIDT) $(UIDLFLAGS) -C $<

.SUFFIXES: .uidl .uidt .uili

#	132

#	144

#	105

#	146

#	284

#	296

#	26

		CC	= cc
		CC	= cc -Aa -D_HPUX_SOURCE

		SLP_SRCS = slptclfe.c slpgetln.c

		SLP_OBJS = slptclfe.o slpgetln.o

		SRCS = ${SLP_SRCS}
		OBJS = ${SLP_OBJS}

.c.o:
		$(RM) $@
		$(CC) -c $(CFLAGS) $*.c

all:: libslp.a

libslp.a:	$(SLP_OBJS)
			$(RM) $@
			$(AR) $@ $(SLP_OBJS)
			$(RANLIB) $@

install::	libslp.a
			$(INSTALL) -C $(INSTLIBFLAGS) libslp.a $(LIBDIR)
			$(RANLIB) $(LIBDIR)/libslp.a

depend::
			$(DEPEND) -s "# DO NOT DELETE" $(CFLAGS) $(SRCS)

clean: :
			$(RM_CMD) \#*

Makefile::	Imakefile \
			$(IRULESRC)/Imake.rules \
			$(IRULESRC)/$(MACROFILE)
			-$(RM) Makefile.bak; $(MV) Makefile Makefile.bak
			$(IMAKE_CMD) -DTOPDIR=$(TOP)

tags::		
			$(TAGS) -tw *.[ch]

.c.o:
			$(RM) $@
			@set -e ;	\
			echo ">>>>> Adding pls id to $<" ;	\
			fname=` echo $< | sed -e 's/\..$$//' `;	\
			vers=`head -1 $<|awk '$$2=="EDITION"{printf "%s %s %s %s\t%s %s %s",$$3,$$4,$$5,$$6,$$7,$$8,$$10}'|	\
					tr '[A-Z]' '[a-z]'`;	\
			issue=`echo $$vers | cut -d\	-f1`; \
			id=$${vers:=’**** (******), *** ***.***\t('`date "+%y/%m/%d %T"`') ******'};	\
			echo "#ifndef PLSID_DEFINED" > $<.id ; \
			echo "#define PLSID_DEFINED" >> $<.id ; \
			echo "static char *whatid = \"@(#)$$fname.$$id\";" >> $<.id ;	\
			echo "static char *plsid = \"$$issue\";" >> $<.id ;	\
			echo "#endif" >> $<.id ; \
			echo "#line 1" >> $<.id ; \
			mv $< $<.C; cat $<.id $<.C > $<; chmod +w $<;	\
			trap '' 2 3 15;	\
			trap 'mv $<.C $<; rm -f $<.id $(<:.c=.o)' ERR; \
			echo $(CC) $(CFLAGS) -c $<;	\
			$(CC) $(CFLAGS) -c $<; mv $<.C $< ; rm -f $<.id

.cxx.o:
			$(RM) $@
				@echo ">>>>>> Adding pls id to $<" ;	\
				fname=` echo $< | sed -e 's/\..$$//' `;	\
				vers=`head -1 $<|awk '$$2=="EDITION"{printf "%s %s %s %s\t%s %s %s",$$3,$$4,$$5,$$6,$$7,$$8,$$10}'| tr '[A-Z]' '[a-z]'`;
				issue=`echo $$vers | cut -d\	-f1`; \
				id=$${vers:='**** (******), *** ***.***\t('`date "+%y/%m/%d %T"`') ******'}; \
				echo "static char *whatid = \"@(#)$$fname.$$id\";" > $*.what_id.c; \
				echo "static char *plsid = \"$$issue\";" >> $*.what_id.c ;	\
			$(CC) $(CFLAGS) -Aa -w -c $*.what_id.c
			$(CC) $(CFLAGS) -c $*.cxx -o $@
			@cat $*.what_id.o >>$@
			@$(RM) $*.what_id.*

#	248

install::
			@echo "install done"

Makefiles::

#	DO NOT DELETE

slptclfe.o: /usr/include/stdlib.h /usr/include/sys/stdsyms.h
slptclfe.o: /usr/include/stdio.h /usr/include/errno.h
slptclfe.o: /usr/include/sys/errno.h /usr/include/string.h
slptclfe.o: /usr/include/sys/types.h /usr/include/sys/stat.h
slptclfe.o: /usr/include/fcntl.h /usr/include/sys/fcntl.h
slptclfe.o: /usr/include/signal.h /usr/include/sys/signal.h
slptclfe.o: /usr/include/sys/syscall.h /usr/include/sys/ioctl.h
slptclfe.o: /usr/include/termios.h /usr/include/sys/termio.h
slptclfe.o: /itdserv/Contexts/g2config.aa07/tcl/inc/tclInt.h
slptclfe.o: /itdserv/Contexts/g2config.aa07/tcl/inc/tcl.h
slptclfe.o: /itdserv/Contexts/g2config.aa07/tcl/inc/tclRegexp.h
slptclfe.o: /usr/include/ctype.h /usr/include/limits.h
slptclfe.o: /usr/include/sys/param.h /usr/include/machine/param.h
slptclfe.o: /usr/include/sys/sysmacros.h /usr/include/sys/time.h
slptclfe.o: /usr/include/varargs.h slp.h
slpgetln.o: /usr/include/stdlib.h /usr/include/sys/stdsyms.h
slpgetln.o: /usr/include/stdio.h /usr/include/unistd.h
slpgetln.o: /usr/include/sys/unistd.h /usr/include/string.h
slpgetln.o: /usr/include/ctype.h /usr/include/errno.h
slpgetln.o: /usr/include/sys/errno.h slp.h
slpgetln.o: /itdserv/Contexts/g2config.aa07/tcl/inc/tcl.h
